spring.application.name=backend

# ============== POSTGRESQL ==============
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/assessmentdb}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root@456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

server.port=${SERVER_PORT:8080}

logging.level.com.grid07=DEBUG
logging.level.org.springframework.data.redis=INFO
spring.main.allow-bean-definition-overriding=true